#version: 2.1
#
#jobs:
#  build:
#    docker:
#      - image: 'circleci/openjdk:8-jdk'
#    steps:
#      - checkout
#      - run:
#          name: Analyze on SonarCloud
#          command: mvn verify sonar:sonar -Dsonar.projectKey=manjudr_scala-circleci-sonar-demo
#
#workflows:
#  main:
#    jobs:
#      - build:
#          context: SonarCloud

version: 2.1
jobs:
  build:
    machine:
      image: ubuntu-2004:202008-01
    steps:
      - checkout
      - run:
          name: Hello World Build
          command: |
            export JAVA_HOME=/usr/lib/jvm/java-1.8.0-openjdk-amd64
            export PATH=$JAVA_HOME/bin:$PATH
            mvn scoverage:report
      - save_cache:
          key: dp-dependency-cache-{{ checksum "data-products/pom.xml" }}
          paths: ~/.m2
      - run:
          name: sonar
          command: |
            export JAVA_HOME=/usr/lib/jvm/java-1.11.0-openjdk-amd64
            mvn -X sonar:sonar -Dsonar.projectKey=manjudr_scala-circleci-sonar-demo  -Dsonar.host.url=https://sonarcloud.io -Dsonar.scala.coverage.reportPaths=/home/circleci/project/data-products/target/scoverage.xml
workflows:
  version: 2.1
  workflow:
    jobs:
      - build